const articles = [
	{	id:"article_20210324-a",
		headline:"Curve Next",
		text:[
			"An interface",
		],	
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(0,0,0,0.0)",
		image_url:"https://curve.metasophiea.com/next/images/wavey_boxes.png",
		link_url:"https://curve.metasophiea.com/next"
	},
	{	id:"article_20180413-a",
		headline:"Curve",
		text:[
			"An interface",
			"(and where I've been spending the last few years)"
		],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,0,0.5)",
		image_url:"/lib/image/mainSiteImagery/curve.png",
		link_url:"https://github.com/metasophiea/curve"
	},
	{	id:"article_20170604-a",
		headline:"RiomhaireRua",
		text:["A fun little VM with 8 bits, 32 commands; and lots of potential for teaching people about how computers work"],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(255,0,0,0.5)",
		image_url:"https://raw.githubusercontent.com/metasophiea/riomhaireRua/master/images/logo.png",
		link_url:"https://github.com/metasophiea/riomhaireRua"
	},
	{	id:"article_20170425-a",
		headline:"Party Calculator",
		text:["Now, we can accurately calculate just how much party there is. Because it's not a party until math is involved"],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,0,0.75)",
		image_url:"/lib/image/mainSiteImagery/partyCalculator.png",
		link_url:"/apps/partyCalculator"
	},
	{	id:"article_20161212-a",
		headline:"P'' Workstation",
		text:[
			"A simple javascript workstation for developing programs in the P'' language",
			//"I plan on developing this tool further, and creating other workstations for more complex assembly languages"
		],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,0,0.75)",
		image_url:"/lib/image/mainSiteImagery/P_code.png",
		link_url:"/apps/virtualMachine/P"
	},
	{	id:"article_20161016-a",
		headline:"SIMON Encryption",
		text:["For my college's final year engineering project, I was asked to implement the SIMON cipher in VHDL. To understand how the cipher works I implemented it in pure Javascript. This site is an encoder/decoder tool for encrypting and decrypting messages using the SIMON cipher","The unencrypted message can be any text, though the encrypted message is hexadecimal as is the password used for encryption"],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,0,0.75)",
		image_url:"/lib/image/mainSiteImagery/SIMONencryption.png",
		link_url:"/apps/encryption/SIMON/translater"
	},
	{	id:"article_20160919-a",
		headline:"Light Cycles",
		text:["Simple but fun game of skill for two players","(red uses Q and W, yellow uses O and P)"],	
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,0,0.0)",
		image_url:"/lib/image/mainSiteImagery/lightcycles.png",
		link_url:"/apps/lightcycles"
	},
	{	id:"article_20160807-a",
		headline:"Canvas Viewing Space Project",
		text:["A pure JS 2d graphics engine, developed into a dynamic presentation app"],
		textcolour:"rgba(0,0,0,1.0)",
		backerFill:"rgba(256,256,256,0.75)",
		image_url:"/lib/image/mainSiteImagery/canvasViewingSpace_splash1.bmp",
		link_url:"/lib/js/canvasViewingSpace"
	},
	{	id:"article_20160807-b",
		headline:"Word Stats",
		text:["A mini webapp showing you some info on things you write in ... not particularly useful, but somewhat handy"],
		textcolour:"rgb(255,255,255)",
		backerFill:"rgba(0,0,100,0.75)",
		image_url:"/lib/image/mainSiteImagery/wordstats_splash1.bmp",
		link_url:"/apps/wordstats"
	},	
	{	id:"article_20160614-a",
		headline:"Free Code Camp Project Archive",
		text:["Check out some of my original websites from when I was first learning HTML, JS and CSS"],
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(255,255,255,0.75)",
		image_url:"/lib/image/mainSiteImagery/freecodecamp_logo.png",
		link_url:"/projects/FreeCodeCamp/"		
	},
	{	id:"article_20161023-a",
		headline:"Nigel",
		text:["An old assembly language project I started a few years ago but decided to stop when I began learning web programming (as I felt that was a more employable skill)","These two posts are taken from my old blogspot blog, and have been recreated here for your reading pleasure. (though Nigel wasn't developed beyond what is there now, part of me would love to return to the project)"],
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(255,255,255,0.75)",
		image_url:"/projects/nigel/images/20150814/16.jpg",
		link_url:"/projects/nigel/"		
	},
	{	id:"article_20160616-a",
		headline:"Soundcloud",
		text:["A small collection of some of the music I've made over the years"],
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(255,128,60,0.65)",
		image_url:"https://4.bp.blogspot.com/-D57hGYq5DY0/VnhfsqXYZbI/AAAAAAAAKyg/YXj6uQf8DnU/s1600/curve_1.bmp",
		link_url:"https://soundcloud.com/metasophiea/"		
	},
	{	id:"article_20160820-a",
		headline:"Github Repository for this Website",
		text:["Ever wonder how all this magic works? Its a bit of a mess, but you can check it out for yourself on the github.com repo"],
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(245,245,245,0.65)",
		image_url:"/lib/image/mainSiteImagery/metasophiea.github.io.png",
		link_url:"https://github.com/metasophiea/metasophiea.github.io"		
	},	
	{	id:"article_20170512-a",
		headline:"The Author's CV",
		text:["For those with a more professional interest"],
		textcolour:"rgb(0,0,0)",
		backerFill:"rgba(256,256,256,0.9)",
		image_url:"/lib/image/mainSiteImagery/CV.png",
		link_url:"/theAuthor/CV/"		
	},
];

console.log('%c'+Object.keys(articles).length+' articles loaded', 'color:rgb(202,136,202); font-style:italic;');
