var URLpreface = 'http://metasophiea.com/apps/partyCalculator/tracks/';
var tracks = [
    [
        URLpreface+'silence.wav',
        URLpreface+'0-drums_01.wav',
        URLpreface+'0-drums_02.wav',
        URLpreface+'0-drums_03.wav',
        URLpreface+'0-drums_04.wav',
        URLpreface+'0-drums_05.wav',
        URLpreface+'0-drums_06.wav',
        URLpreface+'0-drums_07.wav',
        URLpreface+'0-drums_08.wav',
        URLpreface+'0-drums_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'1-bassSynth_01.wav',
        URLpreface+'1-bassSynth_02.wav',
        URLpreface+'1-bassSynth_03.wav',
        URLpreface+'1-bassSynth_04.wav',
        URLpreface+'1-bassSynth_05.wav',
        URLpreface+'1-bassSynth_06.wav',
        URLpreface+'1-bassSynth_07.wav',
        URLpreface+'1-bassSynth_08.wav',
        URLpreface+'1-bassSynth_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'2_mallet_01.wav',
        URLpreface+'2_mallet_02.wav',
        URLpreface+'2_mallet_03.wav',
        URLpreface+'2_mallet_04.wav',
        URLpreface+'2_mallet_05.wav',
        URLpreface+'2_mallet_06.wav',
        URLpreface+'2_mallet_07.wav',
        URLpreface+'2_mallet_08.wav',
        URLpreface+'2_mallet_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'3-synthMelody_01.wav',
        URLpreface+'3-synthMelody_02.wav',
        URLpreface+'3-synthMelody_03.wav',
        URLpreface+'3-synthMelody_04.wav',
        URLpreface+'3-synthMelody_05.wav',
        URLpreface+'3-synthMelody_06.wav',
        URLpreface+'3-synthMelody_07.wav',
        URLpreface+'3-synthMelody_08.wav',
        URLpreface+'3-synthMelody_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'4-piano_01.wav',
        URLpreface+'4-piano_02.wav',
        URLpreface+'4-piano_03.wav',
        URLpreface+'4-piano_04.wav',
        URLpreface+'4-piano_05.wav',
        URLpreface+'4-piano_06.wav',
        URLpreface+'4-piano_07.wav',
        URLpreface+'4-piano_08.wav',
        URLpreface+'4-piano_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'5-strings_01.wav',
        URLpreface+'5-strings_02.wav',
        URLpreface+'5-strings_03.wav',
        URLpreface+'5-strings_04.wav',
        URLpreface+'5-strings_05.wav',
        URLpreface+'5-strings_06.wav',
        URLpreface+'5-strings_07.wav',
        URLpreface+'5-strings_08.wav',
        URLpreface+'5-strings_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'6-fuzz_01.wav',
        URLpreface+'6-fuzz_02.wav',
        URLpreface+'6-fuzz_03.wav',
        URLpreface+'6-fuzz_04.wav',
        URLpreface+'6-fuzz_05.wav',
        URLpreface+'6-fuzz_06.wav',
        URLpreface+'6-fuzz_07.wav',
        URLpreface+'6-fuzz_08.wav',
        URLpreface+'6-fuzz_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'7-electricGuitar_01.wav',
        URLpreface+'7-electricGuitar_02.wav',
        URLpreface+'7-electricGuitar_03.wav',
        URLpreface+'7-electricGuitar_04.wav',
        URLpreface+'7-electricGuitar_05.wav',
        URLpreface+'7-electricGuitar_06.wav',
        URLpreface+'7-electricGuitar_07.wav',
        URLpreface+'7-electricGuitar_08.wav',
        URLpreface+'7-electricGuitar_09.wav'
    ],
    [
        URLpreface+'silence.wav',
        URLpreface+'8-electricLead_01.wav',
        URLpreface+'8-electricLead_02.wav',
        URLpreface+'8-electricLead_03.wav',
        URLpreface+'8-electricLead_04.wav',
        URLpreface+'8-electricLead_05.wav',
        URLpreface+'8-electricLead_06.wav',
        URLpreface+'8-electricLead_07.wav',
        URLpreface+'8-electricLead_08.wav',
        URLpreface+'8-electricLead_09.wav'
    ]
];