var tracks = [
    [
        './tracks/0-drums/0.mp3',
        './tracks/0-drums/1.mp3',
        './tracks/0-drums/2.mp3',
        './tracks/0-drums/3.mp3',
        './tracks/0-drums/4.mp3',
        './tracks/0-drums/5.mp3',
        './tracks/0-drums/6.mp3',
        './tracks/0-drums/7.mp3',
        './tracks/0-drums/8.mp3',
        './tracks/0-drums/9.mp3'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
    [
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-loop-part.wav',
        //'https://raw.githubusercontent.com/fail0verflow/hbc/master/channel/banner/sound/wiibrew-banner-intro-part.wav'
    ],
];